### ISSUE TITLE
Dependencies conflict: scipy, spacy, scikit-learn

### ISSUE THREAD

**Issue by WangariKimotho** [allenai/scruples#6]
Based on the requirements from the setup file there is a conflict with the listed modules, even after updating their versions.

**Comment by Bcopeland64** [comment]
when running the following:

pip install --editable .

I keep receiving the following error:

ERROR: file:///home/brandon does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
 
Are there any workarounds?

**Comment by Bcopeland64** [comment]
Could someone tell me where I may be going wrong with the following error:

error: Setup script exited with error: Command "/usr/bin/f95 -Wall -g -ffixed-form -fno-second-underscore -fPIC -I/home/brandon/anaconda3/lib/python3.9/site-packages/numpy/core/include -c -c scipy/integrate/mach/d1mach.f -o build/temp.linux-x86_64-3.9/scipy/integrate/mach/d1mach.o" failed with exit status 1

From my understanding, I thought there was an issue with scipy, so I updated to the latest release. However, I'm still getting the above-produced error. Any assistance would be greatly appreciated. Thanks

**Comment by nalourie-ai2** [comment]
I've expanded the `requirements.txt` file to pin all dependencies, and added additional constraints to the `setup.py` file that should resolve any conflicts. In addition, I've rewritten the readme's installation instructions to reproduce a fixed environment. If you're still looking to build the environment, try following the readme instructions again.
